In [1]:
import pickle
import numpy as np

In [2]:
with open("./data/total_kbo_player.pkl", "rb") as f:
    kbo_player = pickle.load(f)

In [3]:
for x in kbo_player:
    x['신장'] = x['신장/체중'].split("/")[0].replace("cm", "")
    x['체중'] = x['신장/체중'].split("/")[1].replace("kg", "")

In [4]:
kbo_player[0]

{'선수명': '강동훈',
 '등번호': 'No.034',
 '생년월일': '2000년 11월 23일',
 '포지션': '투수(우투우타)',
 '신장/체중': '185cm/98kg',
 '경력': '천안남산초-청주중-청주고-중앙대',
 '입단 계약금': '7000만원',
 '연봉': '3000만원',
 '지명순위': '24 KIA 5라운드 46순위',
 '입단년도': '',
 'team': 'KIA 타이거즈',
 '신장': '185',
 '체중': '98'}

In [10]:
#kia2 = [x['신장'] for x in kbo_player if x['team'].find("KIA") > -1]

kia = []
for x in kbo_player:
    #팀이름이 기아라면 -1보다 큰 수이므로 
    if x['team'].find("KIA") > -1:
        kia.append(x['신장'])

In [11]:
kia

['185',
 '181',
 '190',
 '178',
 '184',
 '185',
 '187',
 '183',
 '183',
 '184',
 '187',
 '183',
 '188',
 '183',
 '177',
 '186',
 '188',
 '182',
 '182',
 '187',
 '165',
 '180',
 '182',
 '187',
 '176',
 '184',
 '182',
 '180',
 '185',
 '178',
 '183',
 '193',
 '190',
 '193',
 '184',
 '178',
 '180',
 '175',
 '181',
 '178',
 '185',
 '176',
 '180',
 '188',
 '190',
 '183',
 '191',
 '183',
 '172',
 '187',
 '186',
 '185',
 '184',
 '189',
 '181',
 '187',
 '180',
 '188',
 '182',
 '183',
 '187',
 '182',
 '184',
 '182',
 '185',
 '184',
 '177',
 '173',
 '181',
 '184',
 '180',
 '182',
 '178',
 '180',
 '181',
 '182',
 '189',
 '185',
 '192',
 '182',
 '176',
 '178',
 '178',
 '185',
 '184',
 '180',
 '185',
 '174',
 '184',
 '195',
 '178',
 '178',
 '183']

In [12]:
list(map(int, kia))

[185,
 181,
 190,
 178,
 184,
 185,
 187,
 183,
 183,
 184,
 187,
 183,
 188,
 183,
 177,
 186,
 188,
 182,
 182,
 187,
 165,
 180,
 182,
 187,
 176,
 184,
 182,
 180,
 185,
 178,
 183,
 193,
 190,
 193,
 184,
 178,
 180,
 175,
 181,
 178,
 185,
 176,
 180,
 188,
 190,
 183,
 191,
 183,
 172,
 187,
 186,
 185,
 184,
 189,
 181,
 187,
 180,
 188,
 182,
 183,
 187,
 182,
 184,
 182,
 185,
 184,
 177,
 173,
 181,
 184,
 180,
 182,
 178,
 180,
 181,
 182,
 189,
 185,
 192,
 182,
 176,
 178,
 178,
 185,
 184,
 180,
 185,
 174,
 184,
 195,
 178,
 178,
 183]

In [14]:
sum(map(int, kia)) / len(kia)

182.8494623655914

In [15]:
kia_avg = sum(map(int, kia)) / len(kia)

In [18]:
#편차
편차 = [int(x) - kia_avg for x in kia]

In [19]:
편차

[2.1505376344086073,
 -1.8494623655913927,
 7.150537634408607,
 -4.849462365591393,
 1.1505376344086073,
 2.1505376344086073,
 4.150537634408607,
 0.15053763440860735,
 0.15053763440860735,
 1.1505376344086073,
 4.150537634408607,
 0.15053763440860735,
 5.150537634408607,
 0.15053763440860735,
 -5.849462365591393,
 3.1505376344086073,
 5.150537634408607,
 -0.8494623655913927,
 -0.8494623655913927,
 4.150537634408607,
 -17.849462365591393,
 -2.8494623655913927,
 -0.8494623655913927,
 4.150537634408607,
 -6.849462365591393,
 1.1505376344086073,
 -0.8494623655913927,
 -2.8494623655913927,
 2.1505376344086073,
 -4.849462365591393,
 0.15053763440860735,
 10.150537634408607,
 7.150537634408607,
 10.150537634408607,
 1.1505376344086073,
 -4.849462365591393,
 -2.8494623655913927,
 -7.849462365591393,
 -1.8494623655913927,
 -4.849462365591393,
 2.1505376344086073,
 -6.849462365591393,
 -2.8494623655913927,
 5.150537634408607,
 7.150537634408607,
 0.15053763440860735,
 8.150537634408607,
 0.1505

In [21]:
#과학적표기법 = e-13 소수점 기준으로 왼쪽으로 13번 이동 0.00000000xx.. 즉 편차의 합은 0이다
sum(편차)

4.831690603168681e-13

In [25]:
#분산
분산 = sum([x ** 2 for x in 편차])/len(kia)

In [26]:
#표준편차(** 0.5 = 루트)
표준편차 = (sum([x ** 2 for x in 편차])/len(kia)) ** 0.5

In [32]:
print(f"""kia 구단의 평균은 {kia_avg}이고, 분산은 {분산}이며, 표준편차는 {표준편차}입니다.""")

kia 구단의 평균은 182.8494623655914이고, 분산은 23.848306162562157이며, 표준편차는 4.8834727564062606입니다.


In [33]:
sorted(map(int, kia))

[165,
 172,
 173,
 174,
 175,
 176,
 176,
 176,
 177,
 177,
 178,
 178,
 178,
 178,
 178,
 178,
 178,
 178,
 178,
 180,
 180,
 180,
 180,
 180,
 180,
 180,
 180,
 181,
 181,
 181,
 181,
 181,
 182,
 182,
 182,
 182,
 182,
 182,
 182,
 182,
 182,
 182,
 183,
 183,
 183,
 183,
 183,
 183,
 183,
 183,
 183,
 184,
 184,
 184,
 184,
 184,
 184,
 184,
 184,
 184,
 184,
 185,
 185,
 185,
 185,
 185,
 185,
 185,
 185,
 185,
 186,
 186,
 187,
 187,
 187,
 187,
 187,
 187,
 187,
 188,
 188,
 188,
 188,
 189,
 189,
 190,
 190,
 190,
 191,
 192,
 193,
 193,
 195]

In [42]:
sorted(map(int, kia))[int(len(kia) / 2)]

183

In [44]:
kia_np = np.array(list(map(int, kia)))

In [45]:
kia_np

array([185, 181, 190, 178, 184, 185, 187, 183, 183, 184, 187, 183, 188,
       183, 177, 186, 188, 182, 182, 187, 165, 180, 182, 187, 176, 184,
       182, 180, 185, 178, 183, 193, 190, 193, 184, 178, 180, 175, 181,
       178, 185, 176, 180, 188, 190, 183, 191, 183, 172, 187, 186, 185,
       184, 189, 181, 187, 180, 188, 182, 183, 187, 182, 184, 182, 185,
       184, 177, 173, 181, 184, 180, 182, 178, 180, 181, 182, 189, 185,
       192, 182, 176, 178, 178, 185, 184, 180, 185, 174, 184, 195, 178,
       178, 183])

In [48]:
#파이썬에서는 지원해주지않지만, numpy는 지원해줌 = broadcasting 연산 = 벡터연산
kia_np - kia_avg

array([  2.15053763,  -1.84946237,   7.15053763,  -4.84946237,
         1.15053763,   2.15053763,   4.15053763,   0.15053763,
         0.15053763,   1.15053763,   4.15053763,   0.15053763,
         5.15053763,   0.15053763,  -5.84946237,   3.15053763,
         5.15053763,  -0.84946237,  -0.84946237,   4.15053763,
       -17.84946237,  -2.84946237,  -0.84946237,   4.15053763,
        -6.84946237,   1.15053763,  -0.84946237,  -2.84946237,
         2.15053763,  -4.84946237,   0.15053763,  10.15053763,
         7.15053763,  10.15053763,   1.15053763,  -4.84946237,
        -2.84946237,  -7.84946237,  -1.84946237,  -4.84946237,
         2.15053763,  -6.84946237,  -2.84946237,   5.15053763,
         7.15053763,   0.15053763,   8.15053763,   0.15053763,
       -10.84946237,   4.15053763,   3.15053763,   2.15053763,
         1.15053763,   6.15053763,  -1.84946237,   4.15053763,
        -2.84946237,   5.15053763,  -0.84946237,   0.15053763,
         4.15053763,  -0.84946237,   1.15053763,  -0.84

In [43]:
np.mean(list(map(int, kia)))

np.float64(182.8494623655914)

In [49]:
(kia_np - kia_avg).sum()

np.float64(4.831690603168681e-13)

In [50]:
kia_np > 180

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True, False,  True,  True,
       False, False,  True])

In [51]:
kia_np > kia_avg

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True, False, False, False,  True, False,  True, False,
       False,  True, False,  True,  True,  True,  True,  True, False,
       False, False, False, False,  True, False, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True, False,  True,  True, False,  True,
       False,  True,  True, False, False, False,  True, False, False,
       False, False, False, False,  True,  True,  True, False, False,
       False, False,  True,  True, False,  True, False,  True,  True,
       False, False,  True])

In [53]:
#True값만 반환 
kia_np[kia_np > kia_avg]

array([185, 190, 184, 185, 187, 183, 183, 184, 187, 183, 188, 183, 186,
       188, 187, 187, 184, 185, 183, 193, 190, 193, 184, 185, 188, 190,
       183, 191, 183, 187, 186, 185, 184, 189, 187, 188, 183, 187, 184,
       185, 184, 184, 189, 185, 192, 185, 184, 185, 184, 195, 183])

In [55]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [56]:
#형상 확인 
np.array([1,2,3,4]).shape

(4,)

In [57]:
#차원 확인
np.array([1,2,3,4]).ndim

1

In [61]:
#숫자를 만들어줘
np.arange(1,10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [63]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [64]:
np.array([[1,2], [3,4]]).shape

(2, 2)

In [65]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
np.arange(0,12).reshape(3,4).T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [69]:
#배열 내적 연산(선형대수)
np.dot(np.arange(0,12).reshape(3,4), np.arange(0,12).reshape(4,3))

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [71]:
np.arange(0,12).reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
#3차원, 2에 2*2-1(=3)을 만들어줌 
np.arange(0,12).reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [75]:
#리스트 안에 원소가 딕셔너리 형태인 것(반정형) -> 정형데이터로 변환시켜줌 
import pandas as pd

In [76]:
kbo_df = pd.DataFrame(kbo_player)

In [77]:
kbo_df.head(3)

선수명     등번호           생년월일        포지션       신장/체중                    경력  \
0  강동훈  No.034  2000년 11월 23일   투수(우투우타)  185cm/98kg     천안남산초-청주중-청주고-중앙대   
1  강민제  No.038  2005년 02월 10일  내야수(우투우타)  181cm/82kg       군산중앙초-군산중-군산상일고   
2  강이준   No.36  1998년 04월 07일   투수(우투우타)  190cm/86kg  발산초-덕수중-구리인창고-KIA-상무   

   입단 계약금      연봉                 지명순위   입단년도      team   신장  체중  
0  7000만원  3000만원     24 KIA 5라운드 46순위         KIA 타이거즈  185  98  
1  4000만원  3000만원     24 KIA 9라운드 86순위         KIA 타이거즈  181  82  
2  7000만원  3000만원  17 KIA 2차 4라운드 34순위  19KIA  KIA 타이거즈  190  86

In [78]:
import sqlalchemy
from urllib import parse

user = 'encore'
password = '1234'
host='127.0.0.1'
port = 3306
database = 'encore'
password = parse.quote_plus(password)
engine = sqlalchemy.create_engine(f"mysql://{user}:{password}@{host}:{port}/{database}")

In [79]:
kbo_df.to_sql("kbo", if_exists='replace', con=engine)

916