In [2]:
import decorator

In [9]:
def deco(func):
    
    def inner():
        print("running inner function")
        func()
    return inner

In [10]:
@deco
def target():
    print("running target function")

In [11]:
target()

running inner function
running target function


In [12]:
import requests

In [ ]:
r = requests.get("http://127.0.0.1:8000/encore")

In [ ]:
r.json()

### 클래스
1. class란 객체 타입을 정의하는 기능 
2.  클래스를 기반으로 생성된 객체는 인스턴스라고 부름 
3.  같은 클래스의 여러 인스턴스는 같은 특성을 가지면서 각각 독립된 상탵를 유지 

In [25]:
class Encore:
    # __로 시작하는 함수는 내부용 
    #init은 초기함수 
    #self : 이 함수는 클래스에 속한 함수임을 표현 
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def mul(self):
        return self.a * self.b

In [26]:
#object1을 인스턴스라고 부름 / 클래스를 기반으로 생성된 변수 = 객체 
object1 = Encore(30,50)

In [27]:
object1.mul()

1500

In [28]:
object2 = Encore(10,20)

In [29]:
object2.mul()

200

In [43]:
class Car():
    def __init__(self):
        self.엔진 = 5000
        self.기통 = 6
        self.미션 = 6
        self.속도 = 0
    def accelator(self):
        self.속도 += 10
    def dashboard(self):
        print(self.속도)

class Touareg(Car):
    def __init__(self):
        super().__init__()
        
class Urus(Car):
    def __init__(self, 기통):
        super().__init__()
        self.기통 = 기통 

    def display(self):
        print(self.기통)

In [44]:
서진 = Urus(12)

In [45]:
서진.accelator()

In [46]:
서진.display()

12


In [48]:
test = pd.read_csv("./submission.csv")

In [51]:
with open("./mymodel.pkl", "rb") as f:
    mymodel = pickle.load(f)

In [64]:
test.rename(columns = {'Age_x' : 'Age'}, inplace = True)
for _, val in test.iterrows():
    val
    break

In [65]:
_

0

In [66]:
val

Pclass         3.0000
Sex            1.0000
Age           34.5000
SibSp          0.0000
Parch          0.0000
Fare           7.8292
Embarked       1.0000
honorific      4.0000
alone          1.0000
family_num     0.0000
Name: 0, dtype: float64

In [67]:
mymodel

{'columns': Index(['Pclass', 'Sex', 'Age_x', 'SibSp', 'Parch', 'Fare', 'Embarked',
        'honorific', 'alone', 'family_num'],
       dtype='object'),
 'lr': LogisticRegression(),
 'sc': StandardScaler()}

In [68]:
mymodel['sc']

StandardScaler()

In [69]:
val.values.reshape(-1,10)

array([[ 3.    ,  1.    , 34.5   ,  0.    ,  0.    ,  7.8292,  1.    ,
         4.    ,  1.    ,  0.    ]])

In [70]:
mymodel['sc'].transform(val.values.reshape(-1,10))

/home/encore/miniconda3/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 0.81303367,  0.7243102 ,  0.36645016, -0.47072241, -0.47934164,
        -0.47671165, -0.73119328,  0.3117334 ,  0.81220297, -0.55466613]])

In [71]:
val.index

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked',
       'honorific', 'alone', 'family_num'],
      dtype='object')

In [72]:
val.values

array([ 3.    ,  1.    , 34.5   ,  0.    ,  0.    ,  7.8292,  1.    ,
        4.    ,  1.    ,  0.    ])

In [73]:
dict(zip(val.index, val.values))

{'Pclass': np.float64(3.0),
 'Sex': np.float64(1.0),
 'Age': np.float64(34.5),
 'SibSp': np.float64(0.0),
 'Parch': np.float64(0.0),
 'Fare': np.float64(7.8292),
 'Embarked': np.float64(1.0),
 'honorific': np.float64(4.0),
 'alone': np.float64(1.0),
 'family_num': np.float64(0.0)}

In [74]:
#소수점의 값들이 버림으로 됨
dict(zip(val.index, map(int, val.values)))

{'Pclass': 3,
 'Sex': 1,
 'Age': 34,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 7,
 'Embarked': 1,
 'honorific': 4,
 'alone': 1,
 'family_num': 0}

In [78]:
for x in val.index:
    print(val[x])

3.0
1.0
34.5
0.0
0.0
7.8292
1.0
4.0
1.0
0.0


In [80]:
payload = {'Pclass' : 3,
            'Sex' : 1, 
           'Age' : 20, 
           'SibSp' : 1, 
           'Parch' : 1, 
           'Fare' : 10.5, 
           'Embarked' : 1,
           'honorific' : 1, 
           'alone' : 1, 
           'family_num': 1}
r = requests.post("http://222.112.208.67:8000/titanic", json=payload)

In [81]:
test.rename(columns = {'Age_x' : 'Age'}, inplace = True)
for _, val in test.iterrows():
    for x in val.index:
        if x not in ['Fare', 'Age']:
            payload[x] = int(val[x])
        else:
            payload[x] = val[x]
    break

In [87]:
for x1, x2 in zip([1,2,3,4], ['a', 'b', 'c', 'd']):
    print(x1, x2)

1 a
2 b
3 c
4 d
