## OPEN AI가 제공해주는 임베딩 모듈 활용하기(유료결제)

In [ ]:
#openai 인증키를 cmd -> keys.txt -> 입력 후 저장 / key 값 출력
with open("./openai/keys.txt", "r") as f:
    keys = f.read().strip() 

In [ ]:
#openai 연동
import openai 
client = openai.OpenAI(api_key = keys)

In [ ]:
def get_embedding(text, engine):
    #openai 서버에서 res로 데이터 보내줌 
    res = client.embeddings.create(
        input = text
        model = engine
    )
    #보내준 데이터 받기 
    return [d.embedding for d in list(res.data)]

In [ ]:
a = get_embeddings("안녕하세요. 오늘은 월요일입니다.", "text-embedding-ada-002")

In [ ]:
b = get_embeddings("안녕하세요. 오늘은 금요일입니다.", "text-embedding-ada-002")

In [ ]:
#유사도 구하기
import numpy as np 
def cosine_similarity(vec1, vec2):
    #내적
    dot_result = np.dot(vec1, vec2)
    #벡터의 크기로 나눠주기 -> 크기는 numpy norm을 활용 
    dot_result / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

In [ ]:
cosine_similarity(np.array(a[0]), np.array(b[0]))

## Hugging face에서 임베딩 활용하기 (무료제공)
#### 두 자소서 간 유사도 측정

In [3]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('jhgan/ko-sroberta-multitask')

2025-01-06 11:36:57.476634: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-06 11:36:57.495918: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1736131017.510429    2111 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1736131017.515024    2111 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-06 11:36:57.539161: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.86k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/744 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/585 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/248k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/495k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [4]:
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: RobertaModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
)

In [5]:
#벡터 임베딩 테스트 
model.encode(['안녕하세요'])

array([[-1.78593531e-01, -5.61293483e-01,  4.46276575e-01,
        -1.50602862e-01, -3.76699865e-02, -7.62825489e-01,
         2.09378839e-01, -3.64590324e-02,  2.98453033e-01,
        -2.41037279e-01, -6.68550849e-01, -2.28057221e-01,
        -6.40330195e-01,  8.62434506e-02, -1.20845959e-01,
         3.24342489e-01,  2.35195011e-01, -1.59346819e-01,
         3.03968251e-01, -3.05746913e-01,  3.84012043e-01,
         4.27564293e-01,  4.51850116e-01,  6.87622428e-01,
         1.16420604e-01,  6.62420094e-01,  2.50278115e-01,
        -1.45289108e-01,  7.07308710e-01, -2.81398948e-02,
        -6.45834148e-01, -4.65398505e-02, -4.00333017e-01,
        -1.24739092e-02,  3.64073932e-01,  3.63885790e-01,
        -3.57513726e-01, -4.03465509e-01, -3.31616849e-01,
        -1.97075740e-01, -4.95101929e-01,  4.62569222e-02,
         5.58891483e-02,  5.01659274e-01, -3.42604637e-01,
        -9.15144563e-01, -2.68441856e-01, -4.71062124e-01,
        -1.06321178e-01, -1.18266150e-01, -3.35127600e-0

In [10]:
자소서 = """저는 눈앞에 놓인 장애물은 제 길을 가로막는 벽이 아니라 제가 갈 길을 인도해주는 표지판이라고 생각합니다. 왜냐하면 장애물이 없는 곳에는 성장도 없기 때문입니다. 상대적으로 왜소한 체격과 허약한 체질을 가지고 있었던 저는 중학교 시절 운동을 싫어하는 학생이었습니다. 그러다 학생 시절에 진행한 체력장에서 낙제점을 받고 좋아하는 친구 앞에서 망신을 당해야 했습니다. 그 일을 계기로 저는 체력을 기르기 위해 하루가 멀다 하고 운동을 하였고, 고등학생 때는 오래달리기 대표로 나갈 만큼 체력이 좋아졌습니다. 이 일을 계기로 저는 장애물을 넘어서는 재미를 느낄 수 있었습니다. 대학생 때는 C 학점을 받았던 수리통계학을 재수강해서 통계에 흥미를 느끼고 통계학과를 복수전공하였고, 다른 사람 앞에 나서는 것이 두려워 무대에 설 수 있는 춤 동아리에 들어가 무대공포증을 극복했습니다. 이처럼 저는 장애물을 두려워하지 않는, 아니 장애물을 성장의 발판으로 삼는 도전 정신을 가지고 있습니다. 저는 도전 정신을 통해 위기대처능력과 문제에 좌절하지 않는 인내심을 길러왔습니다. 철강 업계의 경쟁은 매년 심화되고 있고 대내외적 환경은 갈수록 악화되고 있습니다. 이런 환경 속에서 도전을 두려워하지 않고 위기를 잘 극복할 수 있는 인재가 필요할 것입니다."""

In [12]:
cover_letter = [x.strip() for x in 자소서.split(".") if len(x) > 0]

In [13]:
cover_letter

['저는 눈앞에 놓인 장애물은 제 길을 가로막는 벽이 아니라 제가 갈 길을 인도해주는 표지판이라고 생각합니다',
 '왜냐하면 장애물이 없는 곳에는 성장도 없기 때문입니다',
 '상대적으로 왜소한 체격과 허약한 체질을 가지고 있었던 저는 중학교 시절 운동을 싫어하는 학생이었습니다',
 '그러다 학생 시절에 진행한 체력장에서 낙제점을 받고 좋아하는 친구 앞에서 망신을 당해야 했습니다',
 '그 일을 계기로 저는 체력을 기르기 위해 하루가 멀다 하고 운동을 하였고, 고등학생 때는 오래달리기 대표로 나갈 만큼 체력이 좋아졌습니다',
 '이 일을 계기로 저는 장애물을 넘어서는 재미를 느낄 수 있었습니다',
 '대학생 때는 C 학점을 받았던 수리통계학을 재수강해서 통계에 흥미를 느끼고 통계학과를 복수전공하였고, 다른 사람 앞에 나서는 것이 두려워 무대에 설 수 있는 춤 동아리에 들어가 무대공포증을 극복했습니다',
 '이처럼 저는 장애물을 두려워하지 않는, 아니 장애물을 성장의 발판으로 삼는 도전 정신을 가지고 있습니다',
 '저는 도전 정신을 통해 위기대처능력과 문제에 좌절하지 않는 인내심을 길러왔습니다',
 '철강 업계의 경쟁은 매년 심화되고 있고 대내외적 환경은 갈수록 악화되고 있습니다',
 '이런 환경 속에서 도전을 두려워하지 않고 위기를 잘 극복할 수 있는 인재가 필요할 것입니다']

In [15]:
corpus_embedding = model.encode(cover_letter, convert_to_tensor=True)

In [17]:
corpus_embedding.shape

torch.Size([11, 768])

In [30]:
queries = "저는 대학교 시절, 다양한 동아리 활동과 프로젝트를 통해 많은 것을 배웠습니다. 특히, 대학 2학년 때 참여한 ‘사회적 기업 프로젝트’가 제 성장에 큰 영향을 미쳤습니다"

In [31]:
query_embedding = model.encode(queries, convert_to_tensor=True)

In [32]:
scores = util.pytorch_cos_sim(query_embedding, corpus_embedding)[0]

In [33]:
scores = scores.cpu()

In [34]:
scores

tensor([0.2146, 0.0519, 0.2922, 0.3397, 0.5015, 0.4633, 0.5236, 0.3779, 0.4568,
        0.1867, 0.3230])

In [35]:
import numpy as np
np.argpartition(-scores, range(3))[0:3]

tensor([6, 4, 5])

In [36]:
[cover_letter[x] for x in np.argpartition(-scores, range(3))[0:3]]

['대학생 때는 C 학점을 받았던 수리통계학을 재수강해서 통계에 흥미를 느끼고 통계학과를 복수전공하였고, 다른 사람 앞에 나서는 것이 두려워 무대에 설 수 있는 춤 동아리에 들어가 무대공포증을 극복했습니다',
 '그 일을 계기로 저는 체력을 기르기 위해 하루가 멀다 하고 운동을 하였고, 고등학생 때는 오래달리기 대표로 나갈 만큼 체력이 좋아졌습니다',
 '이 일을 계기로 저는 장애물을 넘어서는 재미를 느낄 수 있었습니다']

In [40]:
import chromadb, json
with open("./openai/ko_nia_normal_squad_all.json", "r") as f:
    json_text = f.read() 

In [44]:
json_dataset = json.loads(json_text)

In [45]:
json_dataset['data'][0]['paragraphs'][0]['qas'][0]['question']

"서울과 충북 괴산에서 '국제청소년포럼'을 여는 곳은?"

In [48]:
json_dataset['data'][0]['paragraphs'][0]['qas'][0]['answers'][0]['text']

'한국청소년단체협의회와 여성가족부'

In [49]:
dataset_list = []
for idx, data in enumerate(json_dataset['data']):
    for qa in data['paragraphs'][0]['qas']:
        dataset = {}
        dataset['question'] = qa['question']
        dataset['answer']   = qa['answers'][0]['text']
        dataset_list.append(dataset)

In [50]:
import pandas as pd
df = pd.DataFrame(dataset_list)

In [51]:
df

question  \
0                         서울과 충북 괴산에서 '국제청소년포럼'을 여는 곳은?   
1                                   '국제 청소년포럼'이 열리는 때는?   
2                                           이번 포럼의 주제는?   
3                                        포럼은 어떻게 진행되는가?   
4                             아육대에서 리듬체조에 출전한 구구단의 멤버는?   
...                                                 ...   
243420                    현재 사회적 돌봄이 필요한 아동은 몇 명에 이르렀어?   
243421  정부가 2012년부터 전국 초중고교에서 주5일 수업제 전면시행 방침을 밝힌게 언제야?   
243422                   불과 20여만명만이 어디에서 보호와 돌봄을 받고 있어?   
243423              무엇이 전면시행된다면 아동들이 거리에 방치될 우려가 더욱 커져?   
243424  지역아동센터가 주5일 수업제에 따른 돌봄수요를 감당할 수 있으려면 어떻게 해야 한대?   

                                                   answer  
0                                       한국청소년단체협의회와 여성가족부  
1                                               22일부터 28일  
2                                             '청소년과 뉴미디어'  
3       기조강연을 시작으로 국가별 주제관련 사례발표, 그룹 토론 및 전체총회, '청소년선언...  
4                                                      샐리  
...                                                   ...  
243420                                             120여만명  
243421                                             지난 14일  
243422                               지역아동센터와 학교의 종일돌봄교실 등  
243423                                            주5일 수업제  
243424               먼저 토요일 운영을 위한 별도의 재정지원 대책이 마련되어야 한다.  

[243425 rows x 2 columns]

In [53]:
client = chromadb.PersistentClient()

answers = client.create_collection(
    name = "playdata"
)

In [54]:
df = df.iloc[:10000]

In [55]:
df.shape

(10000, 2)

In [63]:
from tqdm import tqdm 
ids = [] 
metadatas = []
embeddings = []
for idx, row in tqdm(enumerate(df.iterrows())):
    query = row[1].question
    answer = row[1].answer
    
    metadata = {
        'query' : query,
        'answer' : answer
    }
    embedding = model.encode(query, normalize_embeddings=True)
    ids.append(str(idx))
    metadatas.append(metadata)
    embeddings.append(embedding)

10000it [05:51, 28.47it/s]


In [69]:
chunk_size = 1024 
total_chunks = len(embeddings) // chunk_size + 1

In [70]:
for chunk_idx in tqdm(range(total_chunks)):
    start_idx = chunk_idx * chunk_size
    end_idx = (chunk_idx +1) * chunk_size

    chunk_embeddings = embeddings[start_idx:end_idx]
    chunk_ids = ids[start_idx:end_idx]
    chunk_metadatas = metadatas[start_idx:end_idx]

    answers.add(embeddings=chunk_embeddings, ids=chunk_ids, metadatas=chunk_metadatas)

100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.55it/s]


In [71]:
answers.query(
    query_embeddings=model.encode("이번 포럼 주제는 뭐야?", normalize_embeddings = True).tolist(),
    n_results=3
)

{'ids': [['2', '3', '5910']],
 'embeddings': None,
 'documents': [[None, None, None]],
 'uris': None,
 'data': None,
 'metadatas': [[{'answer': "'청소년과 뉴미디어'", 'query': '이번 포럼의 주제는?'},
   {'answer': "기조강연을 시작으로 국가별 주제관련 사례발표, 그룹 토론 및 전체총회, '청소년선언문' 작성 및 채택 등 다양한 프로그램을 운영한다.",
    'query': '포럼은 어떻게 진행되는가?'},
   {'answer': '척추관 협착증 치료를 위한 PSLD', 'query': '이번 워크숍의 주제는?'}]],
 'distances': [[0.0609259195625782, 0.3605954945087433, 0.5745532512664795]],
 'included': [<IncludeEnum.distances: 'distances'>,
  <IncludeEnum.documents: 'documents'>,
  <IncludeEnum.metadatas: 'metadatas'>]}

In [ ]:
import chromadb
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('jhgan/ko-sroberta-multitask')

client = chromadb.PersistentClient()

answer = client.get_collection("playdata")

while(True):
    text = input("입력하세요 : ")
    if text == 'Q':
        break
    result = answer.query(
            query_embeddings=model.encode(text, normalize_embeddings=True).tolist(),
            n_results=3)

    for y in [x['answer'] for x in result['metadatas'][0]]:
        print(y)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


입력하세요 :  날씨


기온 1도 등 영상권을 회복하겠습니다.
오수진 기상캐스터
호남 서해안과 제주도


입력하세요 :  날씨


기온 1도 등 영상권을 회복하겠습니다.
오수진 기상캐스터
호남 서해안과 제주도


입력하세요 :  오늘 날씨를 알려줘


내일 서울 아침 기온 영하 13도, 한낮에도 영하 9도에 머물겠고, 금요일까지 아침기온이 영하 15도 안팎을 기록하며 매서운 한파가 예상
기온 1도 등 영상권을 회복하겠습니다.
오수진 기상캐스터
